-- Auditoría e idempotencia de renovaciones de Mercado Pago.
--
-- La primera implementación usaba reports_month_reset como marcador de
-- idempotencia. Ese campo pertenece al cupo mensual y también cambia al generar
-- reportes, por lo que no identifica de forma fiable un cobro.

create table if not exists public.payment_webhook_events (
    id                    bigint generated by default as identity primary key,
    provider              text not null default 'mercadopago',
    event_type            text not null,
    provider_event_id     text not null,
    preapproval_id        text,
    nutri_id              uuid references public.nutris(id) on delete set null,
    processing_status     text not null
                          check (processing_status in ('processed', 'ignored', 'failed')),
    provider_status       text,
    detail                jsonb not null default '{}'::jsonb,
    received_at           timestamptz not null default now(),
    processed_at          timestamptz,
    unique (provider, event_type, provider_event_id)
);

create index if not exists idx_payment_webhook_events_nutri_received
    on public.payment_webhook_events (nutri_id, received_at desc);

create index if not exists idx_payment_webhook_events_status_received
    on public.payment_webhook_events (processing_status, received_at desc);

alter table public.payment_webhook_events enable row level security;

-- Solo el backend (service_role, que bypassa RLS) puede leer o escribir eventos.
revoke all on table public.payment_webhook_events from anon, authenticated;
revoke all on sequence public.payment_webhook_events_id_seq from anon, authenticated;
